version: '3.8'

services:
  youdown:
    build: .
    container_name: youdown_nexovibe
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - DOWNLOAD_PATH=/app/downloads
    restart: unless-stopped
