version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: youdown_api
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      # Use o ficheiro de cookies local (tem de existir)
      - ./cookies.txt:/app/cookies.txt
    environment:
      - DOWNLOAD_PATH=/app/downloads
      - FLASK_HOST=0.0.0.0
    restart: unless-stopped
